name = "bibli"
main = "index.js" # Remplacez par "src/index.js" si votre code est dans un dossier "src"
compatibility_date = "2026-06-27"

# ==============================================================================
# VARIABLES D'ENVIRONNEMENT NON SENSIBLES
# ==============================================================================
[vars]
FIREBASE_PROJECT_ID = "lt-coaching"

# ==============================================================================
# BUCKET R2 (STOCKAGE DES FICHIERS PDF)
# ==============================================================================
[[r2_buckets]]
binding = "MON_BUCKET"
bucket_name = "ma-bibliotheque-fichiers"

# ==============================================================================
# BASE DE DONNÉES CLOUDFLARE D1
# ==============================================================================
[[d1_databases]]
binding = "DB"
database_name = "lt-coaching-db"
database_id = "4af47fa6-a8c4-4433-a27d-90e62aa61b8a"

# ==============================================================================
# DÉCLENCHEUR CRON (REVERSEMENT AUTOMATIQUE LE 15 DU MOIS À 23H59)
# ==============================================================================
[triggers]
crons = ["59 23 15 * *"]

[observability.logs]
enabled = false
invocation_logs = true
